# Site settings
title: Revive Nails & Spa | Professional Nail Care for Ladies & Gentlemen
description: "Professional Nail Care for Ladies & Gentlemen."
baseurl: "" # the subpath of your site, e.g. /blog
url: "revive-nails-and-spa.github.io" # the name of your domain
logo_url: img/revive_logo.png

# Hero
hero: 
    hero_img: hero3.jpg
    hero_title: Revive Nails & Spa
    hero_description: Professional Nail Care for Ladies & Gentlemen.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: (336) 579-9824
    email: support@revivenailsspagso.com
    address: "3912 Battleground Avenue STE 104, Greensboro, NC 27410"

# Opening hours
monday_thursday: 9:30 - 7:30
friday_saturday: 9:00 – 7:30
sunday: 11:30 – 6:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: "3912 Battleground Ave, Greensboro, NC 27410"
    address_details: img/logo.png

# Social settings
facebook: https://www.facebook.com/revivenailsspagso/
# twitter: http://twitter.com
instagram: http://instagram.com/revivenailsspagso
# youtube: http://youtube.com
# skype: skype:obaez_design?userinfo
# feed: yes

# Credit Cards Accepted
ccards: 
    image: cards_accepted.png
    image_alt: "All major credit cards accepts - Pay your way!"

# Footer
copyright: Revive Nails & Spa | All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: true
google_verification:
