# Site settings
title: Revive Nails & Spa | Professional Nail Care for Ladies & Gentlemen
description: "Professional Nail Care for Ladies & Gentlemen."
baseurl: "" # the subpath of your site, e.g. /blog
url: "revive-nails-and-spa.github.io" # the name of your domain
logo_url: img/revive_logo.png

# Hero
hero: 
    hero_img: hero3.jpg
    hero_title: Revive Nails & Spa
    hero_description: Professional Nail Care for Ladies & Gentlemen.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: (336) 579-9824
    email: anthony1@revivenailsandspa.com
    address: "3912 Battleground Avenue STE 104, Greensboro, NC 27410"

# Opening hours
monday: 9:30 am - 7:30 pm
tuesday: Closed
wednesday_thursday: 9:30 am - 7:30 pm
friday_saturday: 9:00 am – 7:30 pm
sunday: 11:30 am – 6:00 pm

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: "3912 Battleground Ave, Greensboro, NC 27410"
    address_details: img/logo.png

# Social settings
facebook: https://www.facebook.com/revivenailsspagso/
# twitter: http://twitter.com
instagram: http://instagram.com/revivenailsspagso
# youtube: http://youtube.com
# skype: skype:obaez_design?userinfo
# feed: yes

# Credit Cards Accepted
ccards: 
    image: cards_accepted.png
    image_alt: "Pay your way!"
    shopsmallbanner:
        image: amex_shop_small_banner.jpg
        image_alt: "We are looking forward to seeing you again! #ShopSmall"
    shopsmallflyer:
        image: amex_shop_small_flyer.jpg
        image_alt: "Thanks to our regulars for continuing to shop small."

# Footer
copyright: Revive Nails & Spa | All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: true
google_reviews: true
google_verification:
